baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ren and Stimpy Classical"
theme = "newsprint"
paginate = 12
ignoreFiles = ["rasc.txt"]
staticDir = ["images"]

[params]
created_with = "created with <a href='https://github.com/naamancampbell/rasc' target='_blank'>rasc</a>"